// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlpd4GqUNHEAyX8u_6HZuauzWYUtqbehs',
    appId: '1:169969358957:web:d006c6835ab96783c08764',
    messagingSenderId: '169969358957',
    projectId: 'test-d8b7c',
    authDomain: 'test-d8b7c.firebaseapp.com',
    storageBucket: 'test-d8b7c.appspot.com',
    measurementId: 'G-5P51JKJL6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH14AWk3LQfkAzWKUr_FbqDbf61hTdFXY',
    appId: '1:169969358957:android:fede14fbd3679069c08764',
    messagingSenderId: '169969358957',
    projectId: 'test-d8b7c',
    storageBucket: 'test-d8b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8g_1kjcYdnyJwNr0CdoPirRsKpQjt-nQ',
    appId: '1:169969358957:ios:7a673e1f4367e9cfc08764',
    messagingSenderId: '169969358957',
    projectId: 'test-d8b7c',
    storageBucket: 'test-d8b7c.appspot.com',
    iosClientId: '169969358957-406our80qrl1dopp4ssmogqih63rrp16.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
